# Generated by Django 4.2.4 on 2023-10-26 16:06

from django.db import migrations


def set_rarity(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')
    items = item_model.objects.all()

    for item_records in items:
        if item_records.price <= 10:
            item_records.rarity = 'Rare'
        elif item_records.price <= 20:
            item_records.rarity = 'Very Rare'
        elif item_records.price <= 30:
            item_records.rarity = 'Extremely Rare'
        else:
            item_records.rarity = 'Mega Rare'

        item_records.save()


def set_rarity_default(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')
    rarity_default = item_model._meta.get_field('rarity').default

    for item in item_model.objects.all():
        item.rarity = rarity_default
        item.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [
        migrations.RunPython(set_rarity, reverse_code=set_rarity_default)
    ]
