# Generated by Django 4.2.4 on 2023-10-26 18:08

from django.db import migrations

MULTIPLY_BY = 120
BIG_PRICE = 750


def set_price(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    smartphones = smartphone_model.objects.all()

    for smartphone_records in smartphones:
        smartphone_records.price = len(smartphone_records.brand) * MULTIPLY_BY
        smartphone_records.save()


def set_price_default(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    price_default = smartphone_model._meta.get_field('price').default
    for smartphone in smartphone_model.objects.all():
        smartphone.price = price_default
        smartphone.save()


def set_category(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    smartphones = smartphone_model.objects.all()

    for smartphone_records in smartphones:
        if smartphone_records.price >= BIG_PRICE:
            smartphone_records.category = 'Expensive'
        else:
            smartphone_records.category = 'Cheap'

def set_category_default(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    category_default = smartphone_model._meta.get_field('category').default

    for smartphone in smartphone_model.objects.all():
        smartphone.category = category_default
        smartphone.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_price, reverse_code=set_price_default),
        migrations.RunPython(set_category, reverse_code=set_category_default)
    ]
