# Generated by Django 4.2.4 on 2023-10-27 02:57

from django.db import migrations
from django.utils import timezone

DEFAULT_DELIVERY = None
DEFAULT_WARRANTY = "No warranty"
def set_delivery_and_warranty(apps, schema_editor):
    order_model = apps.get_model('main_app', 'Order')
    orders = order_model.objects.all()

    for order in orders:
        if order.status == 'Pending':
            order.delivery = order.order_date + timezone.timedelta(days=3)
            order.save()
        elif order.status == 'Completed':
            order.warranty = '24 months'
            order.save()
        elif order.status == 'Cancelled':
            order.delete()

def set_delivery_warranty_default(apps, schema_editor):
    order_model = apps.get_model('main_app', 'Order')
    orders = order_model.objects.all()

    for order in orders:
        if order.status == 'Pending':
            order.delivery = DEFAULT_DELIVERY
        elif order.status == 'Completed':
            order.warranty = DEFAULT_WARRANTY
        order.save()

class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0015_order'),
    ]

    operations = [
        migrations.RunPython(set_delivery_and_warranty, reverse_code=set_delivery_warranty_default)
    ]
