# Generated by Django 4.2.4 on 2023-11-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(error_messages={'invalid', 'Enter a valid email address'}, max_length=254),
        ),
    ]
