# Generated by Django 4.2.4 on 2023-11-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_book_movie_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='music',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
