# Generated by Django 4.2.4 on 2023-10-19 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_in_days', models.PositiveIntegerField(verbose_name='Duration in Days')),
                ('estimated_hours', models.FloatField(verbose_name='Estimated Hours')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_edited_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='last_edited_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='location',
            field=models.CharField(blank=True, choices=[('sof', 'Sofia'), ('pl', 'Plovdiv'), ('bur', 'Burgas'), ('var', 'Varna')], max_length=20, null=True),
        ),
    ]
