# Generated by Django 4.2.4 on 2023-11-21 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='realestatelisting',
            managers=[
            ],
        ),
    ]
