# Generated by Django 4.2.4 on 2023-10-21 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_person_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
