# Generated by Django 4.2.4 on 2023-11-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_bird_mammal_reptile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='birth_day',
            new_name='birth_date',
        ),
    ]
