# Generated by Django 4.2.4 on 2023-10-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('As', 'Asus'), ('Ac', 'Acer'), ('Ap', 'Apple'), ('Le', 'Lenovo'), ('De', 'Dell')])),
                ('processor', models.CharField(max_length=100)),
                ('memory', models.PositiveIntegerField(help_text='Memory in GB')),
                ('storage', models.PositiveIntegerField(help_text='Storage in GB')),
                ('operation_system', models.CharField(choices=[('W', 'Windows'), ('M', 'MacOS'), ('L', 'Linux'), ('Ch', 'Chrome OS')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
